apiVersion: v1
kind: ConfigMap
metadata:
  name: tb-node-db-config
  namespace: thingsboard
  labels:
    name: tb-node-db-config
data:
  DATABASE_TS_TYPE: cassandra
  DATABASE_ENTITIES_TYPE: cassandra
  CASSANDRA_URL: cassandra:9042
  CASSANDRA_SOCKET_READ_TIMEOUT: "60000"
