version: '2.2'

services:
  postgres:
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
  tb1:
    volumes:
      - tb-log-volume:/var/log/thingsboard
  tb2:
    volumes:
      - tb-log-volume:/var/log/thingsboard
  tb-coap-transport:
    volumes:
      - tb-coap-transport-log-volume:/var/log/tb-coap-transport
  tb-http-transport1:
    volumes:
      - tb-http-transport-log-volume:/var/log/tb-http-transport
  tb-http-transport2:
    volumes:
      - tb-http-transport-log-volume:/var/log/tb-http-transport
  tb-mqtt-transport1:
    volumes:
      - tb-mqtt-transport-log-volume:/var/log/tb-mqtt-transport
  tb-mqtt-transport2:
    volumes:
      - tb-mqtt-transport-log-volume:/var/log/tb-mqtt-transport

volumes:
  postgres-db-volume:
    external: true
    name: ${POSTGRES_DATA_VOLUME}
  tb-log-volume:
    external: true
    name: ${TB_LOG_VOLUME}
  tb-coap-transport-log-volume:
    external: true
    name: ${TB_COAP_TRANSPORT_LOG_VOLUME}
  tb-http-transport-log-volume:
    external: true
    name: ${TB_HTTP_TRANSPORT_LOG_VOLUME}
  tb-mqtt-transport-log-volume:
    external: true
    name: ${TB_MQTT_TRANSPORT_LOG_VOLUME}
